version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_USER=apiAccess
      - MONGODB_PASSWORD=dyLJpsCo33rCgVE9
      - MONGODB_HOST=easy-gym
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run start:dev"
